/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author LAB_Sistemas_ITH
 */
public class Visualizar_Modelado_IFRM extends javax.swing.JInternalFrame {

    /**
     * Creates new form Visualizar_Modelado_IFRM
     */
    public Visualizar_Modelado_IFRM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bg_DiagramaUML = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        diagrama_UML = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Visualizar Diagrama UML");

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_DiagramaUML.setBackground(new java.awt.Color(51, 204, 0));
        bg_DiagramaUML.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bg_DiagramaUML.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(32, 32, 32));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 32, 32));
        jLabel2.setText("DIAGRAMA UML");
        bg_DiagramaUML.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 30));

        bg.add(bg_DiagramaUML, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        diagrama_UML.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        diagrama_UML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleado_Cheque_Herencia_UMLv1.2.png"))); // NOI18N
        bg.add(diagrama_UML, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg_DiagramaUML;
    private javax.swing.JLabel diagrama_UML;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
